import clsx from "clsx";
import { type NextPage } from "next";
import { Manrope } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";

type Advice = {
  id: number;
  advice: string;
};

const manrope = Manrope({ subsets: ["latin"] });

const Home: NextPage = () => {
  const [advice, setAdvice] = useState<Advice>();
  const [loading, setLoading] = useState(false);

  async function getAdvice() {
    setLoading(true);
    const res = await fetch("https://api.adviceslip.com/advice");
    const adv = (await res.json()) as { slip: Advice };
    setLoading(false);
    setAdvice(adv.slip);
  }

  useEffect(() => {
    void getAdvice();
  }, []);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${manrope.className} grid h-screen w-screen place-items-center overflow-hidden`}
      >
        <div className="relative m-4 w-[450px] rounded-2xl bg-dark-grayish-blue p-10">
          <h4 className="mb-6 text-center text-[11px] font-extrabold uppercase tracking-[0.4em] text-neon-green/80">
            Advice #{advice?.id}
          </h4>
          <blockquote className="text-center text-xl font-bold tracking-wide text-light-cyan">
            “{advice?.advice}”
          </blockquote>
          <div className="mb-4 mt-7 flex items-center">
            <div className="mr-4 h-px grow bg-grayish-blue" />
            <div className="mr-1.5 h-3.5 w-1 rounded bg-light-cyan" />
            <div className="h-3.5 w-1 rounded bg-light-cyan" />
            <div className="ml-4 h-px grow bg-grayish-blue" />
          </div>
          <button
            className={clsx(
              "absolute -bottom-5 left-[calc(50%-22px)] grid h-11 w-11 place-items-center rounded-full bg-neon-green hover:shadow-[0_0_40px_-3px] hover:shadow-neon-green",
              loading && "animate-spin ease-in"
            )}
            onClick={() => void getAdvice()}
          >
            <Image src="/icon-dice.svg" width={16} height={16} alt="" />
          </button>
        </div>
      </div>
    </>
  );
};

export default Home;
